-- ============================================================
-- Database: smart_failure_detection
-- Description: Complete schema for Smart Failure Detection with ML
-- Milestone 2: Risk Assessment & SWOT Analysis
-- ============================================================

-- Create the database (if not exists)
-- Uncomment if you need to create the database
-- CREATE DATABASE smart_failure_detection;
-- \c smart_failure_detection;

-- ============================================================
-- EXTENSIONS
-- ============================================================

-- Enable UUID generation if needed for future features
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enable pgcrypto for password hashing
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- DROP EXISTING TABLES (in correct order to avoid dependency issues)
-- ============================================================

DROP VIEW IF EXISTS vw_Dashboard_Statistics CASCADE;
DROP VIEW IF EXISTS vw_Project_Complete_Assessment CASCADE;
DROP TABLE IF EXISTS Assessment_Report_Contents CASCADE;
DROP TABLE IF EXISTS AI_Analysis_History CASCADE;
DROP TABLE IF EXISTS User_Sessions CASCADE;
DROP TABLE IF EXISTS Assessment_Reports CASCADE;
DROP TABLE IF EXISTS Recommendations CASCADE;
DROP TABLE IF EXISTS Success_Predictions CASCADE;
DROP TABLE IF EXISTS SWOT_Analysis CASCADE;
DROP TABLE IF EXISTS Risk_Assessments CASCADE;
DROP TABLE IF EXISTS Competitor_Analysis CASCADE;
DROP TABLE IF EXISTS Analytics CASCADE;
DROP TABLE IF EXISTS Analytics_Logs CASCADE;
DROP TABLE IF EXISTS Projects CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

-- ============================================================
-- TABLE: Users
-- ============================================================
-- Purpose: Stores registered users of the project system
-- ============================================================

CREATE TABLE IF NOT EXISTS Users (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(50) NOT NULL DEFAULT 'user',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    last_login      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_user_role CHECK (role IN ('admin', 'analyst', 'user', 'viewer'))
);

-- Indexes for Users table
CREATE INDEX idx_users_email_001 ON Users(email);
CREATE INDEX idx_users_role_001 ON Users(role);
CREATE INDEX idx_users_created_at_001 ON Users(created_at DESC);

-- Comment on Users table and columns
COMMENT ON TABLE Users IS 'Stores registered users of the project system';
COMMENT ON COLUMN Users.user_id IS 'Auto-generated unique identifier for the user';
COMMENT ON COLUMN Users.name IS 'Full name of the user';
COMMENT ON COLUMN Users.email IS 'Email address of the user (unique)';
COMMENT ON COLUMN Users.password_hash IS 'Hashed password using bcrypt or similar algorithm';
COMMENT ON COLUMN Users.role IS 'User role: admin, analyst, user, or viewer';
COMMENT ON COLUMN Users.is_active IS 'Flag to indicate if the user account is active';
COMMENT ON COLUMN Users.last_login IS 'Timestamp of the users last login';
COMMENT ON COLUMN Users.created_at IS 'Timestamp when the user was created';
COMMENT ON COLUMN Users.updated_at IS 'Timestamp when the user record was last updated';

-- ============================================================
-- TABLE: Projects
-- ============================================================
-- Purpose: Stores the core information submitted for each project
-- ============================================================

CREATE TABLE IF NOT EXISTS Projects (
    project_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    project_name        VARCHAR(255) NOT NULL,
    project_type        VARCHAR(100),
    industry            VARCHAR(100),
    business_model      VARCHAR(100),
    budget              NUMERIC(15, 2) CHECK (budget >= 0),
    target_market       TEXT,
    description         TEXT,
    status              VARCHAR(50) NOT NULL DEFAULT 'submitted',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) 
        REFERENCES Users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    
    CONSTRAINT chk_project_status CHECK (status IN ('submitted', 'analyzing', 'completed', 'archived'))
);

-- Indexes for Projects table
CREATE INDEX idx_projects_user_id_001 ON Projects(user_id);
CREATE INDEX idx_projects_created_at_001 ON Projects(created_at DESC);
CREATE INDEX idx_projects_status_001 ON Projects(status);
CREATE INDEX idx_projects_industry_001 ON Projects(industry);
CREATE INDEX idx_projects_business_model_001 ON Projects(business_model);
CREATE INDEX idx_projects_project_type_001 ON Projects(project_type);
CREATE INDEX idx_projects_user_status_001 ON Projects(user_id, status);

-- Comment on Projects table and columns
COMMENT ON TABLE Projects IS 'Stores the core information submitted for each project';
COMMENT ON COLUMN Projects.project_id IS 'Auto-generated unique identifier for the project';
COMMENT ON COLUMN Projects.user_id IS 'Reference to the user who submitted the project';
COMMENT ON COLUMN Projects.project_name IS 'Name of the startup or project';
COMMENT ON COLUMN Projects.project_type IS 'Type/category of the project';
COMMENT ON COLUMN Projects.industry IS 'Industry or sector classification';
COMMENT ON COLUMN Projects.business_model IS 'Business model type (B2B, B2C, SaaS, etc.)';
COMMENT ON COLUMN Projects.budget IS 'Project budget in USD';
COMMENT ON COLUMN Projects.target_market IS 'Target customer segment or market';
COMMENT ON COLUMN Projects.description IS 'Detailed project description and objectives';
COMMENT ON COLUMN Projects.status IS 'Current status of the project: submitted, analyzing, completed, archived';
COMMENT ON COLUMN Projects.created_at IS 'Timestamp when the project was submitted';
COMMENT ON COLUMN Projects.updated_at IS 'Timestamp when the project record was last updated';

-- ============================================================
-- TABLE: Analytics_Logs
-- ============================================================
-- Purpose: Stores user/system activity logs for analytics and auditing
-- ============================================================

CREATE TABLE IF NOT EXISTS Analytics_Logs (
    log_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    session_id      VARCHAR(100),
    activity_type   VARCHAR(100) NOT NULL,
    activity_detail JSONB,
    ip_address      INET,
    user_agent      TEXT,
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_logs_user FOREIGN KEY (user_id) 
        REFERENCES Users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT chk_activity_type CHECK (activity_type IN (
        'login', 'logout', 'project_submit', 'project_view', 'project_update', 
        'analysis_view', 'report_generate', 'dashboard_view', 'search', 
        'filter_apply', 'export_data', 'settings_update', 'password_change'
    ))
);

-- Indexes for Analytics_Logs table
CREATE INDEX idx_logs_user_id_001 ON Analytics_Logs(user_id);
CREATE INDEX idx_logs_timestamp_001 ON Analytics_Logs(timestamp DESC);
CREATE INDEX idx_logs_activity_type_001 ON Analytics_Logs(activity_type);
CREATE INDEX idx_logs_user_timestamp_001 ON Analytics_Logs(user_id, timestamp DESC);
CREATE INDEX idx_logs_activity_timestamp_001 ON Analytics_Logs(activity_type, timestamp DESC);
CREATE INDEX idx_logs_ip_address_001 ON Analytics_Logs(ip_address);

-- Comment on Analytics_Logs table and columns
COMMENT ON TABLE Analytics_Logs IS 'Stores user/system activity logs for analytics and auditing';
COMMENT ON COLUMN Analytics_Logs.log_id IS 'Auto-generated unique identifier for the log entry';
COMMENT ON COLUMN Analytics_Logs.user_id IS 'Reference to the user who performed the activity';
COMMENT ON COLUMN Analytics_Logs.session_id IS 'Unique session identifier for tracking user sessions';
COMMENT ON COLUMN Analytics_Logs.activity_type IS 'Type of activity performed by the user';
COMMENT ON COLUMN Analytics_Logs.activity_detail IS 'JSONB field storing additional details about the activity';
COMMENT ON COLUMN Analytics_Logs.ip_address IS 'IP address of the user at the time of activity';
COMMENT ON COLUMN Analytics_Logs.user_agent IS 'Browser/device information of the user';
COMMENT ON COLUMN Analytics_Logs.timestamp IS 'Timestamp when the activity occurred';

-- ============================================================
-- TABLE: Analytics
-- ============================================================
-- Purpose: Stores analytical information generated from project data
-- ============================================================

CREATE TABLE IF NOT EXISTS Analytics (
    usg_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT NOT NULL,
    project_type    VARCHAR(100),
    project_budget  NUMERIC(15, 2) CHECK (project_budget >= 0),
    markets         JSONB,
    industry_insights JSONB,
    market_trends   JSONB,
    analysis_version VARCHAR(20),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_analytics_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indexes for Analytics table
CREATE INDEX idx_analytics_project_id_001 ON Analytics(project_id);
CREATE INDEX idx_analytics_generated_at_001 ON Analytics(generated_at DESC);
CREATE INDEX idx_analytics_project_type_001 ON Analytics(project_type);
CREATE INDEX idx_analytics_created_at_001 ON Analytics(created_at DESC);

-- Comment on Analytics table and columns
COMMENT ON TABLE Analytics IS 'Stores analytical information generated from project data';
COMMENT ON COLUMN Analytics.usg_id IS 'Auto-generated unique identifier for the analytics record';
COMMENT ON COLUMN Analytics.project_id IS 'Reference to the project being analyzed';
COMMENT ON COLUMN Analytics.project_type IS 'Type/category of the project for analytical purposes';
COMMENT ON COLUMN Analytics.project_budget IS 'Budget of the project used for analytical calculations';
COMMENT ON COLUMN Analytics.markets IS 'JSONB field storing market information and target markets';
COMMENT ON COLUMN Analytics.industry_insights IS 'JSONB field storing industry-specific insights and analysis';
COMMENT ON COLUMN Analytics.market_trends IS 'JSONB field storing market trend analysis data';
COMMENT ON COLUMN Analytics.analysis_version IS 'Version of the analysis engine used to generate this data';
COMMENT ON COLUMN Analytics.created_at IS 'Timestamp when the analytics record was created';
COMMENT ON COLUMN Analytics.generated_at IS 'Timestamp when the analysis was generated';

-- ============================================================
-- TABLE: Competitor_Analysis
-- ============================================================
-- Purpose: Stores competitor and market analysis for a project
-- ============================================================

CREATE TABLE IF NOT EXISTS Competitor_Analysis (
    analysis_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT NOT NULL,
    competitor_name   VARCHAR(255) NOT NULL,
    market_position   VARCHAR(100),
    competitive_risk  VARCHAR(20),
    competitor_insights JSONB,
    analysis_date     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_competitor_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT chk_competitive_risk CHECK (competitive_risk IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
);

-- Indexes for Competitor_Analysis table
CREATE INDEX idx_competitor_project_id_001 ON Competitor_Analysis(project_id);
CREATE INDEX idx_competitor_analysis_date_001 ON Competitor_Analysis(analysis_date DESC);
CREATE INDEX idx_competitor_competitive_risk_001 ON Competitor_Analysis(competitive_risk);
CREATE INDEX idx_competitor_name_001 ON Competitor_Analysis(competitor_name);
CREATE INDEX idx_competitor_project_risk_001 ON Competitor_Analysis(project_id, competitive_risk);

-- Comment on Competitor_Analysis table and columns
COMMENT ON TABLE Competitor_Analysis IS 'Stores competitor and market analysis for a project';
COMMENT ON COLUMN Competitor_Analysis.analysis_id IS 'Auto-generated unique identifier for the competitor analysis record';
COMMENT ON COLUMN Competitor_Analysis.project_id IS 'Reference to the project being analyzed';
COMMENT ON COLUMN Competitor_Analysis.competitor_name IS 'Name of the competitor being analyzed';
COMMENT ON COLUMN Competitor_Analysis.market_position IS 'Position of the competitor in the market';
COMMENT ON COLUMN Competitor_Analysis.competitive_risk IS 'Risk level posed by this competitor: LOW, MEDIUM, HIGH, CRITICAL';
COMMENT ON COLUMN Competitor_Analysis.competitor_insights IS 'JSONB field storing detailed insights about the competitor';
COMMENT ON COLUMN Competitor_Analysis.analysis_date IS 'Timestamp when the competitor analysis was performed';

-- ============================================================
-- TABLE: Risk_Assessments
-- ============================================================
-- Purpose: Stores risk analysis generated for each project
-- Core Milestone 2 table
-- ============================================================

CREATE TABLE IF NOT EXISTS Risk_Assessments (
    risk_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT NOT NULL,
    risk_category     VARCHAR(50) NOT NULL,
    risk_score        INTEGER NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
    risk_description  TEXT NOT NULL,
    risk_impact       TEXT,
    risk_likelihood   VARCHAR(20),
    priority_level    VARCHAR(20) NOT NULL,
    mitigation_strategy TEXT,
    assessed_by       BIGINT,
    assessment_date   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_risk_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_risk_assessed_by FOREIGN KEY (assessed_by) 
        REFERENCES Users(user_id) ON DELETE SET NULL ON UPDATE CASCADE,
    
    CONSTRAINT chk_risk_category CHECK (risk_category IN (
        'Financial', 'Market', 'Technical', 'Business', 'Execution', 
        'Operational', 'Regulatory', 'Reputational', 'Strategic'
    )),
    
    CONSTRAINT chk_priority_level CHECK (priority_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    
    CONSTRAINT chk_risk_likelihood CHECK (risk_likelihood IN ('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH'))
);

-- Indexes for Risk_Assessments table
CREATE INDEX idx_risk_project_id_001 ON Risk_Assessments(project_id);
CREATE INDEX idx_risk_category_001 ON Risk_Assessments(risk_category);
CREATE INDEX idx_risk_score_001 ON Risk_Assessments(risk_score);
CREATE INDEX idx_risk_priority_001 ON Risk_Assessments(priority_level);
CREATE INDEX idx_risk_assessment_date_001 ON Risk_Assessments(assessment_date DESC);
CREATE INDEX idx_risk_project_category_001 ON Risk_Assessments(project_id, risk_category);
CREATE INDEX idx_risk_score_priority_001 ON Risk_Assessments(risk_score DESC, priority_level);

-- Comment on Risk_Assessments table and columns
COMMENT ON TABLE Risk_Assessments IS 'Stores risk analysis generated for each project - Core Milestone 2 table';
COMMENT ON COLUMN Risk_Assessments.risk_id IS 'Auto-generated unique identifier for the risk assessment record';
COMMENT ON COLUMN Risk_Assessments.project_id IS 'Reference to the project being assessed';
COMMENT ON COLUMN Risk_Assessments.risk_category IS 'Category of risk: Financial, Market, Technical, Business, Execution, etc.';
COMMENT ON COLUMN Risk_Assessments.risk_score IS 'Risk score from 0 to 100 representing the severity/impact';
COMMENT ON COLUMN Risk_Assessments.risk_description IS 'Detailed description of the risk';
COMMENT ON COLUMN Risk_Assessments.risk_impact IS 'Description of potential impact if the risk materializes';
COMMENT ON COLUMN Risk_Assessments.risk_likelihood IS 'Likelihood of the risk occurring: VERY_LOW, LOW, MEDIUM, HIGH, VERY_HIGH';
COMMENT ON COLUMN Risk_Assessments.priority_level IS 'Priority level of the risk: LOW, MEDIUM, HIGH, CRITICAL';
COMMENT ON COLUMN Risk_Assessments.mitigation_strategy IS 'Recommended strategy to mitigate the risk';
COMMENT ON COLUMN Risk_Assessments.assessed_by IS 'Reference to the user who performed the risk assessment';
COMMENT ON COLUMN Risk_Assessments.assessment_date IS 'Timestamp when the risk assessment was performed';

-- ============================================================
-- TABLE: SWOT_Analysis
-- ============================================================
-- Purpose: Stores automatically generated SWOT analysis
-- Core Milestone 2 table
-- ============================================================

CREATE TABLE IF NOT EXISTS SWOT_Analysis (
    swot_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       BIGINT NOT NULL,
    strengths        JSONB NOT NULL,
    weaknesses       JSONB NOT NULL,
    opportunities    JSONB NOT NULL,
    threats          JSONB NOT NULL,
    analysis_version VARCHAR(20),
    generated_by     BIGINT,
    generated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_swot_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_swot_generated_by FOREIGN KEY (generated_by) 
        REFERENCES Users(user_id) ON DELETE SET NULL ON UPDATE CASCADE,
    
    CONSTRAINT chk_swot_strengths CHECK (jsonb_array_length(strengths) > 0),
    CONSTRAINT chk_swot_weaknesses CHECK (jsonb_array_length(weaknesses) > 0),
    CONSTRAINT chk_swot_opportunities CHECK (jsonb_array_length(opportunities) > 0),
    CONSTRAINT chk_swot_threats CHECK (jsonb_array_length(threats) > 0)
);

-- Indexes for SWOT_Analysis table
CREATE INDEX idx_swot_project_id_001 ON SWOT_Analysis(project_id);
CREATE INDEX idx_swot_generated_at_001 ON SWOT_Analysis(generated_at DESC);
CREATE INDEX idx_swot_project_generated_001 ON SWOT_Analysis(project_id, generated_at DESC);
CREATE INDEX idx_swot_analysis_version_001 ON SWOT_Analysis(analysis_version);

-- Comment on SWOT_Analysis table and columns
COMMENT ON TABLE SWOT_Analysis IS 'Stores automatically generated SWOT analysis - Core Milestone 2 table';
COMMENT ON COLUMN SWOT_Analysis.swot_id IS 'Auto-generated unique identifier for the SWOT analysis record';
COMMENT ON COLUMN SWOT_Analysis.project_id IS 'Reference to the project being analyzed';
COMMENT ON COLUMN SWOT_Analysis.strengths IS 'JSONB array of strengths identified in the analysis';
COMMENT ON COLUMN SWOT_Analysis.weaknesses IS 'JSONB array of weaknesses identified in the analysis';
COMMENT ON COLUMN SWOT_Analysis.opportunities IS 'JSONB array of opportunities identified in the analysis';
COMMENT ON COLUMN SWOT_Analysis.threats IS 'JSONB array of threats identified in the analysis';
COMMENT ON COLUMN SWOT_Analysis.analysis_version IS 'Version of the SWOT analysis engine used';
COMMENT ON COLUMN SWOT_Analysis.generated_by IS 'Reference to the user who generated the SWOT analysis';
COMMENT ON COLUMN SWOT_Analysis.generated_at IS 'Timestamp when the SWOT analysis was generated';

-- ============================================================
-- TABLE: Success_Predictions
-- ============================================================
-- Purpose: Stores predictive results generated by ML/predictive analysis
-- ============================================================

CREATE TABLE IF NOT EXISTS Success_Predictions (
    prediction_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id           BIGINT NOT NULL,
    success_probability  NUMERIC(5, 2) NOT NULL CHECK (success_probability >= 0 AND success_probability <= 100),
    overall_risk_score   INTEGER NOT NULL CHECK (overall_risk_score >= 0 AND overall_risk_score <= 100),
    confidence_score     NUMERIC(5, 2) CHECK (confidence_score >= 0 AND confidence_score <= 100),
    prediction_metrics   JSONB,
    model_version        VARCHAR(50),
    prediction_date      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_prediction_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indexes for Success_Predictions table
CREATE INDEX idx_prediction_project_id_001 ON Success_Predictions(project_id);
CREATE INDEX idx_prediction_date_001 ON Success_Predictions(prediction_date DESC);
CREATE INDEX idx_prediction_success_rate_001 ON Success_Predictions(success_probability DESC);
CREATE INDEX idx_prediction_risk_score_001 ON Success_Predictions(overall_risk_score);
CREATE INDEX idx_prediction_project_date_001 ON Success_Predictions(project_id, prediction_date DESC);

-- Comment on Success_Predictions table and columns
COMMENT ON TABLE Success_Predictions IS 'Stores predictive results generated by ML/predictive analysis';
COMMENT ON COLUMN Success_Predictions.prediction_id IS 'Auto-generated unique identifier for the prediction record';
COMMENT ON COLUMN Success_Predictions.project_id IS 'Reference to the project being predicted';
COMMENT ON COLUMN Success_Predictions.success_probability IS 'Probability of success from 0 to 100 (percentage)';
COMMENT ON COLUMN Success_Predictions.overall_risk_score IS 'Overall risk score from 0 to 100';
COMMENT ON COLUMN Success_Predictions.confidence_score IS 'Confidence level of the prediction from 0 to 100';
COMMENT ON COLUMN Success_Predictions.prediction_metrics IS 'JSONB field storing additional prediction metrics and details';
COMMENT ON COLUMN Success_Predictions.model_version IS 'Version of the ML model used for prediction';
COMMENT ON COLUMN Success_Predictions.prediction_date IS 'Timestamp when the prediction was made';

-- ============================================================
-- TABLE: Recommendations
-- ============================================================
-- Purpose: Stores recommendations and risk mitigation suggestions
-- ============================================================

CREATE TABLE IF NOT EXISTS Recommendations (
    recommendation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT NOT NULL,
    recommendation_text TEXT NOT NULL,
    recommendation_type VARCHAR(50),
    risk_mitigation     TEXT,
    priority            VARCHAR(20) NOT NULL,
    category            VARCHAR(50),
    target_area         VARCHAR(100),
    expected_impact     TEXT,
    implementation_steps JSONB,
    generated_by        BIGINT,
    generated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_applied          BOOLEAN NOT NULL DEFAULT FALSE,
    applied_at          TIMESTAMPTZ,
    
    CONSTRAINT fk_recommendation_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_recommendation_generated_by FOREIGN KEY (generated_by) 
        REFERENCES Users(user_id) ON DELETE SET NULL ON UPDATE CASCADE,
    
    CONSTRAINT chk_recommendation_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    
    CONSTRAINT chk_recommendation_type CHECK (recommendation_type IN (
        'strategic', 'tactical', 'operational', 'risk_mitigation', 'growth', 'compliance'
    ))
);

-- Indexes for Recommendations table
CREATE INDEX idx_recommendation_project_id_001 ON Recommendations(project_id);
CREATE INDEX idx_recommendation_priority_001 ON Recommendations(priority);
CREATE INDEX idx_recommendation_generated_at_001 ON Recommendations(generated_at DESC);
CREATE INDEX idx_recommendation_type_001 ON Recommendations(recommendation_type);
CREATE INDEX idx_recommendation_category_001 ON Recommendations(category);
CREATE INDEX idx_recommendation_project_priority_001 ON Recommendations(project_id, priority);
CREATE INDEX idx_recommendation_is_applied_001 ON Recommendations(is_applied);

-- Comment on Recommendations table and columns
COMMENT ON TABLE Recommendations IS 'Stores recommendations and risk mitigation suggestions generated by the system';
COMMENT ON COLUMN Recommendations.recommendation_id IS 'Auto-generated unique identifier for the recommendation';
COMMENT ON COLUMN Recommendations.project_id IS 'Reference to the project receiving the recommendation';
COMMENT ON COLUMN Recommendations.recommendation_text IS 'Detailed recommendation text';
COMMENT ON COLUMN Recommendations.recommendation_type IS 'Type of recommendation: strategic, tactical, operational, etc.';
COMMENT ON COLUMN Recommendations.risk_mitigation IS 'Risk mitigation guidance related to the recommendation';
COMMENT ON COLUMN Recommendations.priority IS 'Priority level: LOW, MEDIUM, HIGH, CRITICAL';
COMMENT ON COLUMN Recommendations.category IS 'Category of the recommendation';
COMMENT ON COLUMN Recommendations.target_area IS 'Specific area the recommendation addresses';
COMMENT ON COLUMN Recommendations.expected_impact IS 'Expected impact of implementing the recommendation';
COMMENT ON COLUMN Recommendations.implementation_steps IS 'JSONB array of steps to implement the recommendation';
COMMENT ON COLUMN Recommendations.generated_by IS 'Reference to the user who generated the recommendation';
COMMENT ON COLUMN Recommendations.generated_at IS 'Timestamp when the recommendation was generated';
COMMENT ON COLUMN Recommendations.is_applied IS 'Flag indicating if the recommendation has been applied';
COMMENT ON COLUMN Recommendations.applied_at IS 'Timestamp when the recommendation was applied';

-- ============================================================
-- TABLE: Assessment_Reports
-- ============================================================
-- Purpose: Stores references to generated project assessment reports
-- ============================================================

CREATE TABLE IF NOT EXISTS Assessment_Reports (
    report_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id         BIGINT NOT NULL,
    report_path        VARCHAR(500) NOT NULL,
    report_format      VARCHAR(20) NOT NULL DEFAULT 'PDF',
    report_size        BIGINT,
    report_metadata    JSONB,
    generated_by       BIGINT,
    generated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    download_count     INTEGER NOT NULL DEFAULT 0,
    last_downloaded_at TIMESTAMPTZ,
    
    CONSTRAINT fk_report_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT fk_report_generated_by FOREIGN KEY (generated_by) 
        REFERENCES Users(user_id) ON DELETE SET NULL ON UPDATE CASCADE,
    
    CONSTRAINT chk_report_format CHECK (report_format IN ('PDF', 'DOCX', 'HTML', 'JSON'))
);

-- Indexes for Assessment_Reports table
CREATE INDEX idx_report_project_id_001 ON Assessment_Reports(project_id);
CREATE INDEX idx_report_generated_at_001 ON Assessment_Reports(generated_at DESC);
CREATE INDEX idx_report_format_001 ON Assessment_Reports(report_format);
CREATE INDEX idx_report_project_date_001 ON Assessment_Reports(project_id, generated_at DESC);

-- Comment on Assessment_Reports table and columns
COMMENT ON TABLE Assessment_Reports IS 'Stores references to generated project assessment reports';
COMMENT ON COLUMN Assessment_Reports.report_id IS 'Auto-generated unique identifier for the report record';
COMMENT ON COLUMN Assessment_Reports.project_id IS 'Reference to the project the report is for';
COMMENT ON COLUMN Assessment_Reports.report_path IS 'Path, URL, or storage key to the report file';
COMMENT ON COLUMN Assessment_Reports.report_format IS 'Format of the report: PDF, DOCX, HTML, JSON';
COMMENT ON COLUMN Assessment_Reports.report_size IS 'Size of the report file in bytes';
COMMENT ON COLUMN Assessment_Reports.report_metadata IS 'JSONB field storing additional report metadata';
COMMENT ON COLUMN Assessment_Reports.generated_by IS 'Reference to the user who generated the report';
COMMENT ON COLUMN Assessment_Reports.generated_at IS 'Timestamp when the report was generated';
COMMENT ON COLUMN Assessment_Reports.download_count IS 'Number of times the report has been downloaded';
COMMENT ON COLUMN Assessment_Reports.last_downloaded_at IS 'Timestamp of the last download';

-- ============================================================
-- TABLE: Assessment_Report_Contents
-- ============================================================
-- Purpose: Stores structured content from assessment reports for querying
-- ============================================================

CREATE TABLE IF NOT EXISTS Assessment_Report_Contents (
    content_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id         BIGINT NOT NULL,
    content_section   VARCHAR(100) NOT NULL,
    content_data      JSONB NOT NULL,
    content_order     INTEGER NOT NULL,
    
    CONSTRAINT fk_report_content FOREIGN KEY (report_id) 
        REFERENCES Assessment_Reports(report_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT chk_content_section CHECK (content_section IN (
        'executive_summary', 'project_details', 'risk_assessment', 'swot_analysis', 
        'success_prediction', 'recommendations', 'competitor_analysis', 'financial_analysis',
        'market_analysis', 'conclusion'
    ))
);

-- Indexes for Assessment_Report_Contents table
CREATE INDEX idx_report_content_report_id_001 ON Assessment_Report_Contents(report_id);
CREATE INDEX idx_report_content_section_001 ON Assessment_Report_Contents(content_section);

-- Comment on Assessment_Report_Contents table
COMMENT ON TABLE Assessment_Report_Contents IS 'Stores structured content from assessment reports for querying and analysis';

-- ============================================================
-- TABLE: User_Sessions
-- ============================================================
-- Purpose: Manages user login sessions
-- ============================================================

CREATE TABLE IF NOT EXISTS User_Sessions (
    session_id        VARCHAR(255) PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    token             VARCHAR(500) NOT NULL,
    expires_at        TIMESTAMPTZ NOT NULL,
    ip_address        INET,
    user_agent        TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) 
        REFERENCES Users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indexes for User_Sessions table
CREATE INDEX idx_session_user_id_001 ON User_Sessions(user_id);
CREATE INDEX idx_session_expires_at_001 ON User_Sessions(expires_at);
CREATE INDEX idx_session_token_001 ON User_Sessions(token);

-- Comment on User_Sessions table
COMMENT ON TABLE User_Sessions IS 'Manages user login sessions for authentication and authorization';

-- ============================================================
-- TABLE: AI_Analysis_History
-- ============================================================
-- Purpose: Tracks AI analysis operations for auditing and improvement
-- ============================================================

CREATE TABLE IF NOT EXISTS AI_Analysis_History (
    analysis_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT NOT NULL,
    analysis_type     VARCHAR(50) NOT NULL,
    input_data        JSONB,
    output_data       JSONB,
    model_used        VARCHAR(100),
    processing_time   INTEGER,
    status            VARCHAR(20) NOT NULL DEFAULT 'processing',
    error_message     TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at      TIMESTAMPTZ,
    
    CONSTRAINT fk_ai_analysis_project FOREIGN KEY (project_id) 
        REFERENCES Projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT chk_analysis_type CHECK (analysis_type IN (
        'risk_assessment', 'swot_generation', 'success_prediction', 
        'recommendation_generation', 'report_generation', 'competitor_analysis'
    )),
    
    CONSTRAINT chk_analysis_status CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
);

-- Indexes for AI_Analysis_History table
CREATE INDEX idx_ai_analysis_project_id_001 ON AI_Analysis_History(project_id);
CREATE INDEX idx_ai_analysis_type_001 ON AI_Analysis_History(analysis_type);
CREATE INDEX idx_ai_analysis_status_001 ON AI_Analysis_History(status);
CREATE INDEX idx_ai_analysis_created_at_001 ON AI_Analysis_History(created_at DESC);

-- Comment on AI_Analysis_History table
COMMENT ON TABLE AI_Analysis_History IS 'Tracks AI analysis operations for auditing, debugging, and improvement';

-- ============================================================
-- VIEW: vw_Project_Complete_Assessment
-- ============================================================
-- Purpose: Provides a comprehensive view of all assessment data for a project
-- ============================================================

CREATE OR REPLACE VIEW vw_Project_Complete_Assessment AS
SELECT 
    p.project_id,
    p.project_name,
    p.industry,
    p.business_model,
    p.budget,
    p.status,
    p.created_at as project_submitted_at,
    u.name as owner_name,
    u.email as owner_email,
    
    -- Latest Risk Assessment
    ra.risk_score as latest_overall_risk_score,
    ra.assessment_date as latest_risk_assessment_date,
    
    -- Latest SWOT Analysis
    swot.strengths,
    swot.weaknesses,
    swot.opportunities,
    swot.threats,
    swot.generated_at as swot_generated_at,
    
    -- Latest Success Prediction
    sp.success_probability,
    sp.confidence_score,
    sp.prediction_date,
    
    -- Assessment Report
    ar.report_path,
    ar.generated_at as report_generated_at,
    ar.download_count as report_download_count
    
FROM Projects p
JOIN Users u ON p.user_id = u.user_id
LEFT JOIN LATERAL (
    SELECT * FROM Risk_Assessments 
    WHERE project_id = p.project_id 
    ORDER BY assessment_date DESC LIMIT 1
) ra ON true
LEFT JOIN LATERAL (
    SELECT * FROM SWOT_Analysis 
    WHERE project_id = p.project_id 
    ORDER BY generated_at DESC LIMIT 1
) swot ON true
LEFT JOIN LATERAL (
    SELECT * FROM Success_Predictions 
    WHERE project_id = p.project_id 
    ORDER BY prediction_date DESC LIMIT 1
) sp ON true
LEFT JOIN LATERAL (
    SELECT * FROM Assessment_Reports 
    WHERE project_id = p.project_id 
    ORDER BY generated_at DESC LIMIT 1
) ar ON true;

COMMENT ON VIEW vw_Project_Complete_Assessment IS 'Provides a comprehensive view of all assessment data for a project';

-- ============================================================
-- VIEW: vw_Dashboard_Statistics
-- ============================================================
-- Purpose: Provides dashboard statistics for the application
-- ============================================================

CREATE OR REPLACE VIEW vw_Dashboard_Statistics AS
SELECT
    (SELECT COUNT(*) FROM Users WHERE is_active = true) as total_active_users,
    (SELECT COUNT(*) FROM Users) as total_users,
    (SELECT COUNT(*) FROM Projects) as total_projects,
    (SELECT COUNT(*) FROM Projects WHERE status = 'submitted') as pending_projects,
    (SELECT COUNT(*) FROM Projects WHERE status = 'analyzing') as analyzing_projects,
    (SELECT COUNT(*) FROM Projects WHERE status = 'completed') as completed_projects,
    (SELECT COALESCE(AVG(risk_score), 0) FROM Risk_Assessments) as average_risk_score,
    (SELECT COALESCE(AVG(success_probability), 0) FROM Success_Predictions) as average_success_rate,
    (SELECT COUNT(*) FROM Assessment_Reports WHERE generated_at > NOW() - INTERVAL '30 days') as reports_last_30_days,
    (SELECT COUNT(*) FROM Analytics_Logs WHERE timestamp > NOW() - INTERVAL '24 hours') as activities_last_24_hours;

COMMENT ON VIEW vw_Dashboard_Statistics IS 'Provides dashboard statistics for the application';

-- ============================================================
-- SAMPLE DATA
-- ============================================================

-- 1. Sample User
INSERT INTO Users (name, email, password_hash, role, is_active) 
VALUES 
('John Doe', 'john.doe@example.com', crypt('SecurePass123!', gen_salt('bf')), 'admin', true),
('Jane Smith', 'jane.smith@example.com', crypt('SecurePass123!', gen_salt('bf')), 'analyst', true),
('Bob Wilson', 'bob.wilson@example.com', crypt('SecurePass123!', gen_salt('bf')), 'user', true);

-- 2. Sample Project
INSERT INTO Projects (user_id, project_name, project_type, industry, business_model, budget, target_market, description, status) 
VALUES 
(1, 'AI-Powered Health Diagnostics', 'startup', 'Healthcare', 'B2B', 250000, 'Hospitals and Clinics', 
 'An AI-powered platform for early disease detection using machine learning algorithms to analyze medical imaging data.', 'completed');

-- 3. Sample Analytics
INSERT INTO Analytics (project_id, project_type, project_budget, markets, industry_insights, market_trends, analysis_version) 
VALUES 
(1, 'healthtech', 250000, '{"primary": "Healthcare Providers", "secondary": "Diagnostic Centers"}', 
 '{"market_size": "Growing", "competition": "Medium", "barriers": "Regulatory"}',
 '{"trends": ["AI Adoption", "Digital Health", "Telemedicine"], "growth_rate": 15.5}', 'v1.0');

-- 4. Sample Risk Assessment
INSERT INTO Risk_Assessments (project_id, risk_category, risk_score, risk_description, risk_impact, risk_likelihood, priority_level, mitigation_strategy) 
VALUES 
(1, 'Market', 65, 'Competition from established healthcare tech companies with larger market share and more resources.', 
 'Potential difficulty in acquiring market share and building brand recognition.', 'HIGH', 'HIGH', 
 'Focus on niche segments and build strong partnerships with smaller healthcare providers.'),

(1, 'Financial', 45, 'Limited initial funding for extended R&D and market entry.', 
 'Potential cash flow issues during development phase.', 'MEDIUM', 'MEDIUM',
 'Seek additional funding through grants and angel investors. Consider phased rollout.'),

(1, 'Technical', 35, 'Complexity of ML models and need for high accuracy in medical diagnostics.', 
 'Risk of inaccurate diagnoses leading to liability issues.', 'LOW', 'MEDIUM',
 'Implement robust validation and testing protocols. Partner with medical institutions for validation.'),

(1, 'Regulatory', 55, 'Strict healthcare regulations and FDA approval requirements.', 
 'Potential delays in product launch and increased compliance costs.', 'HIGH', 'MEDIUM',
 'Engage regulatory consultants early. Plan for a longer development timeline with regulatory compliance in mind.');

-- 5. Sample SWOT Analysis
INSERT INTO SWOT_Analysis (project_id, strengths, weaknesses, opportunities, threats, analysis_version) 
VALUES 
(1, 
 '["Strong AI/ML expertise", "Innovative diagnostic approach", "Scalable platform architecture", "Potential for early detection", "Reduced healthcare costs"]',
 '["Limited regulatory experience", "Need for large training datasets", "Competition from established players", "High R&D costs"]',
 '["Growing telehealth market", "Aging population", "Healthcare digitization trends", "AI acceptance in medical field", "Potential for global expansion"]',
 '["Regulatory challenges", "Competition from Big Tech", "Data privacy concerns", "Changing healthcare policies", "Fast-moving technology landscape"]',
 'v1.0');

-- 6. Sample Success Prediction
INSERT INTO Success_Predictions (project_id, success_probability, overall_risk_score, confidence_score, prediction_metrics, model_version) 
VALUES 
(1, 72.50, 50, 85.00, 
 '{"accuracy": 0.85, "precision": 0.82, "recall": 0.88, "f1_score": 0.85, "features_used": ["industry", "budget", "competition", "team_experience"]}',
 'v1.0');

-- 7. Sample Recommendations
INSERT INTO Recommendations (project_id, recommendation_text, recommendation_type, risk_mitigation, priority, category, target_area, implementation_steps) 
VALUES 
(1, 
 'Develop a phased market entry strategy starting with a pilot program in partnership with a regional healthcare network.', 
 'strategic',
 'This approach allows for validation of the product in a controlled environment, reducing market entry risks and building credibility before scaling.', 
 'HIGH',
 'Market Strategy',
 'Market Entry',
 '["Identify potential pilot partners", "Define pilot scope and success metrics", "Negotiate partnership agreement", "Execute pilot program", "Collect and analyze feedback", "Refine product based on learnings", "Scale gradually"]'),

(1,
 'Engage regulatory consultants early and plan for FDA approval process with a realistic timeline.',
 'risk_mitigation',
 'Early regulatory engagement helps identify potential compliance issues before they become costly problems, reducing overall project risk.',
 'HIGH',
 'Compliance',
 'Regulatory',
 '["Hire regulatory consultant", "Map out regulatory requirements", "Create compliance checklist", "Integrate compliance into development", "Schedule regulatory review checkpoints", "Prepare documentation"]'),

(1,
 'Invest in developing partnerships with medical institutions for access to diverse training datasets.',
 'tactical',
 'Access to quality training data is crucial for ML model accuracy and reduces the risk of biased or inaccurate diagnostic results.',
 'MEDIUM',
 'Technical',
 'Data Acquisition',
 '["Research potential partners", "Define data requirements", "Establish data sharing agreements", "Implement data privacy protocols", "Collect and curate datasets", "Validate data quality"]');

-- 8. Sample Assessment Report
INSERT INTO Assessment_Reports (project_id, report_path, report_format, report_size, report_metadata) 
VALUES 
(1, '/reports/project_1_assessment_20250115.pdf', 'PDF', 2547896, 
 '{"pages": 15, "sections": ["Executive Summary", "Project Overview", "Risk Assessment", "SWOT Analysis", "Success Prediction", "Recommendations", "Conclusion"], "generator": "AI Report Engine v1.0"}');

-- 9. Sample Analytics Log
INSERT INTO Analytics_Logs (user_id, activity_type, activity_detail, ip_address, user_agent) 
VALUES 
(1, 'project_submit', '{"project_id": 1, "project_name": "AI-Powered Health Diagnostics"}', '192.168.1.100', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0'),
(1, 'analysis_view', '{"project_id": 1, "view_type": "complete_assessment"}', '192.168.1.100', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0'),
(2, 'report_generate', '{"project_id": 1, "report_type": "pdf"}', '192.168.1.101', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/121.0');

-- ============================================================
-- SAMPLE QUERIES
-- ============================================================

-- Query 1: Get complete assessment for a project
SELECT 
    p.project_id,
    p.project_name,
    p.industry,
    p.business_model,
    p.budget,
    u.name as owner_name,
    u.email as owner_email,
    ra.risk_score,
    ra.risk_category,
    ra.priority_level as risk_priority,
    swot.strengths,
    swot.weaknesses,
    swot.opportunities,
    swot.threats,
    sp.success_probability,
    sp.overall_risk_score,
    sp.confidence_score,
    ar.report_path,
    ar.generated_at as report_generated_at
FROM Projects p
JOIN Users u ON p.user_id = u.user_id
LEFT JOIN Risk_Assessments ra ON p.project_id = ra.project_id
LEFT JOIN SWOT_Analysis swot ON p.project_id = swot.project_id
LEFT JOIN Success_Predictions sp ON p.project_id = sp.project_id
LEFT JOIN Assessment_Reports ar ON p.project_id = ar.project_id
WHERE p.project_id = 1
ORDER BY ra.assessment_date DESC, swot.generated_at DESC, sp.prediction_date DESC, ar.generated_at DESC
LIMIT 1;

-- Query 2: Get all risk assessments for a project with category breakdown
SELECT 
    risk_category,
    COUNT(*) as risk_count,
    AVG(risk_score) as avg_score,
    MAX(risk_score) as max_score,
    MIN(risk_score) as min_score,
    priority_level,
    string_agg(DISTINCT risk_description, '; ') as risk_descriptions
FROM Risk_Assessments
WHERE project_id = 1
GROUP BY risk_category, priority_level
ORDER BY avg_score DESC;

-- Query 3: Get project analytics summary
SELECT 
    COUNT(*) as total_projects,
    AVG(p.budget) as avg_budget,
    SUM(p.budget) as total_budget,
    AVG(sp.success_probability) as avg_success_rate,
    AVG(sp.overall_risk_score) as avg_risk_score,
    COUNT(DISTINCT p.industry) as unique_industries,
    COUNT(DISTINCT p.business_model) as unique_business_models,
    COUNT(DISTINCT p.user_id) as unique_users
FROM Projects p
LEFT JOIN Success_Predictions sp ON p.project_id = sp.project_id
WHERE p.status = 'completed';

-- Query 4: Get detailed SWOT analysis for a project with categories
SELECT 
    swot_id,
    jsonb_array_elements_text(strengths) as strength,
    jsonb_array_elements_text(weaknesses) as weakness,
    jsonb_array_elements_text(opportunities) as opportunity,
    jsonb_array_elements_text(threats) as threat,
    generated_at
FROM SWOT_Analysis
WHERE project_id = 1
ORDER BY generated_at DESC
LIMIT 1;

-- Query 5: Get recommendations by priority for a project
SELECT 
    recommendation_text,
    priority,
    category,
    target_area,
    is_applied,
    generated_at
FROM Recommendations
WHERE project_id = 1
ORDER BY 
    CASE priority 
        WHEN 'CRITICAL' THEN 1 
        WHEN 'HIGH' THEN 2 
        WHEN 'MEDIUM' THEN 3 
        WHEN 'LOW' THEN 4 
    END,
    generated_at DESC;

-- Query 6: Get user activity summary
SELECT 
    u.user_id,
    u.name,
    u.email,
    u.role,
    COUNT(DISTINCT p.project_id) as total_projects,
    COUNT(DISTINCT al.log_id) as total_activities,
    MAX(al.timestamp) as last_activity,
    COUNT(DISTINCT ar.report_id) as total_reports
FROM Users u
LEFT JOIN Projects p ON u.user_id = p.user_id
LEFT JOIN Analytics_Logs al ON u.user_id = al.user_id
LEFT JOIN Assessment_Reports ar ON p.project_id = ar.project_id
WHERE u.is_active = true
GROUP BY u.user_id, u.name, u.email, u.role
ORDER BY total_projects DESC;

-- Query 7: Get dashboard statistics using the view
SELECT * FROM vw_Dashboard_Statistics;

-- Query 8: Get comprehensive project assessment using the view
SELECT * FROM vw_Project_Complete_Assessment WHERE project_id = 1;