-- ===================================================
-- MILESTONE 2 - COMPLETE DATABASE SCHEMA
-- AI-Powered Product Intelligence System
-- ===================================================

-- Enable UUID extension for better security
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ===================================================
-- 1. USERS TABLE
-- ===================================================
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(50) DEFAULT 'user' NOT NULL,
    is_active BOOLEAN DEFAULT true,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Stores registered users of the system';
COMMENT ON COLUMN users.password_hash IS 'Bcrypt or Argon2 hashed password';
COMMENT ON COLUMN users.role IS 'User role: admin, analyst, user';

-- ===================================================
-- 2. PROJECTS TABLE
-- ===================================================
CREATE TABLE IF NOT EXISTS projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    project_type VARCHAR(100),
    industry VARCHAR(100),
    business_model VARCHAR(100),
    target_market TEXT,
    budget NUMERIC(15, 2),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_projects_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE projects IS 'Stores core project information submitted by users';
COMMENT ON COLUMN projects.budget IS 'Project budget in USD';

-- ===================================================
-- 3. ANALYTICS_LOGS TABLE
-- ===================================================
CREATE TABLE IF NOT EXISTS analytics_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    activity_type VARCHAR(100) NOT NULL,
    activity_details JSONB,
    ip_address INET,
    user_agent TEXT,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analytics_logs_users FOREIGN KEY (user_id) 
        REFERENCES users(user_id) ON DELETE SET NULL ON UPDATE CASCADE
);

COMMENT ON TABLE analytics_logs IS 'Stores user/system activity logs for analytics and auditing';
COMMENT ON COLUMN analytics_logs.activity_details IS 'JSONB field for additional activity context';

-- ===================================================
-- 4. ANALYTICS TABLE
-- ===================================================
CREATE TABLE IF NOT EXISTS analytics (
    usg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    project_type VARCHAR(100),
    project_budget NUMERIC(15, 2),
    markets JSONB,
    industry VARCHAR(100),
    analysis_data JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analytics_projects FOREIGN KEY (project_id) 
        REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE analytics IS 'Stores analytical information generated from project data';
COMMENT ON COLUMN analytics.markets IS 'JSONB array of target markets';
COMMENT ON COLUMN analytics.analysis_data IS 'JSONB field for flexible analysis data storage';

-- ===================================================
-- 5. COMPETITOR_ANALYSIS TABLE
-- ===================================================
CREATE TABLE IF NOT EXISTS competitor_analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    competitor_name VARCHAR(255) NOT NULL,
    market_position VARCHAR(50),
    competitive_risk VARCHAR(20) CHECK (competitive_risk IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    analysis_details JSONB,
    analysis_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_competitor_analysis_projects FOREIGN KEY (project_id) 
        REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE competitor_analysis IS 'Stores competitor and market analysis for projects';
COMMENT ON COLUMN competitor_analysis.competitive_risk IS 'Risk level: LOW, MEDIUM, HIGH, CRITICAL';

-- ===================================================
-- 6. RISK_ASSESSMENTS TABLE (CORE MILESTONE 2)
-- ===================================================
CREATE TABLE IF NOT EXISTS risk_assessments (
    risk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    risk_category VARCHAR(50) NOT NULL CHECK (risk_category IN (
        'Financial', 'Market', 'Technical', 'Business', 'Execution', 
        'Operational', 'Regulatory', 'Strategic', 'Competitive'
    )),
    risk_score INTEGER CHECK (risk_score >= 0 AND risk_score <= 100),
    risk_description TEXT,
    impact_assessment TEXT,
    priority_level VARCHAR(20) CHECK (priority_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    mitigation_strategy TEXT,
    assessment_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_risk_assessments_projects FOREIGN KEY (project_id) 
        REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE risk_assessments IS 'Stores risk analysis generated for each project (Milestone 2 Core)';
COMMENT ON COLUMN risk_assessments.risk_score IS 'Risk score from 0-100';
COMMENT ON COLUMN risk_assessments.priority_level IS 'Priority: LOW, MEDIUM, HIGH, CRITICAL';

-- ===================================================
-- 7. SWOT_ANALYSIS TABLE (CORE MILESTONE 2)
-- ===================================================
CREATE TABLE IF NOT EXISTS swot_analysis (
    swot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    strengths JSONB NOT NULL,
    weaknesses JSONB NOT NULL,
    opportunities JSONB NOT NULL,
    threats JSONB NOT NULL,
    summary TEXT,
    generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_latest BOOLEAN DEFAULT true,
    CONSTRAINT fk_swot_analysis_projects FOREIGN KEY (project_id) 
        REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE swot_analysis IS 'Stores automatically generated SWOT analysis (Milestone 2 Core)';
COMMENT ON COLUMN swot_analysis.strengths IS 'JSONB array of strengths';
COMMENT ON COLUMN swot_analysis.weaknesses IS 'JSONB array of weaknesses';
COMMENT ON COLUMN swot_analysis.opportunities IS 'JSONB array of opportunities';
COMMENT ON COLUMN swot_analysis.threats IS 'JSONB array of threats';
COMMENT ON COLUMN swot_analysis.is_latest IS 'Flag to identify the most recent SWOT analysis';

-- ===================================================
-- 8. SUCCESS_PREDICTIONS TABLE (CORE MILESTONE 2)
-- ===================================================
CREATE TABLE IF NOT EXISTS success_predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    success_probability INTEGER CHECK (success_probability >= 0 AND success_probability <= 100),
    overall_risk_score INTEGER CHECK (overall_risk_score >= 0 AND overall_risk_score <= 100),
    confidence_score INTEGER CHECK (confidence_score >= 0 AND confidence_score <= 100),
    prediction_details JSONB,
    prediction_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_latest BOOLEAN DEFAULT true,
    CONSTRAINT fk_success_predictions_projects FOREIGN KEY (project_id) 
        REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE success_predictions IS 'Stores predictive results from ML/predictive analysis (Milestone 2 Core)';
COMMENT ON COLUMN success_predictions.success_probability IS 'Success probability from 0-100';
COMMENT ON COLUMN success_predictions.overall_risk_score IS 'Overall risk score from 0-100';
COMMENT ON COLUMN success_predictions.confidence_score IS 'Confidence level in the prediction from 0-100';
COMMENT ON COLUMN success_predictions.is_latest IS 'Flag to identify the most recent prediction';

-- ===================================================
-- 9. RECOMMENDATIONS TABLE (CORE MILESTONE 2)
-- ===================================================
CREATE TABLE IF NOT EXISTS recommendations (
    recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    recommendation_text TEXT NOT NULL,
    category VARCHAR(100),
    risk_mitigation TEXT,
    priority VARCHAR(20) CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    expected_impact TEXT,
    implementation_steps JSONB,
    generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_latest BOOLEAN DEFAULT true,
    CONSTRAINT fk_recommendations_projects FOREIGN KEY (project_id) 
        REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE recommendations IS 'Stores recommendations and risk mitigation suggestions (Milestone 2 Core)';
COMMENT ON COLUMN recommendations.implementation_steps IS 'JSONB array of implementation steps';

-- ===================================================
-- 10. ASSESSMENT_REPORTS TABLE
-- ===================================================
CREATE TABLE IF NOT EXISTS assessment_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    report_path TEXT NOT NULL,
    report_type VARCHAR(50) DEFAULT 'PDF',
    report_summary TEXT,
    generated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_latest BOOLEAN DEFAULT true,
    CONSTRAINT fk_assessment_reports_projects FOREIGN KEY (project_id) 
        REFERENCES projects(project_id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMENT ON TABLE assessment_reports IS 'Stores references to generated project assessment reports';
COMMENT ON COLUMN assessment_reports.report_path IS 'Path, URL, or object-storage key to the report';

-- ===================================================
-- INDEXES FOR PERFORMANCE (WITH EXISTENCE CHECKS)
-- ===================================================

-- Users indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_users_email') THEN
        CREATE INDEX idx_users_email ON users(email);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_users_role') THEN
        CREATE INDEX idx_users_role ON users(role);
    END IF;
END $$;

-- Projects indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_projects_user_id') THEN
        CREATE INDEX idx_projects_user_id ON projects(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_projects_industry') THEN
        CREATE INDEX idx_projects_industry ON projects(industry);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_projects_created_at') THEN
        CREATE INDEX idx_projects_created_at ON projects(created_at DESC);
    END IF;
END $$;

-- Analytics logs indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_analytics_logs_user_id') THEN
        CREATE INDEX idx_analytics_logs_user_id ON analytics_logs(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_analytics_logs_timestamp') THEN
        CREATE INDEX idx_analytics_logs_timestamp ON analytics_logs(timestamp DESC);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_analytics_logs_activity_type') THEN
        CREATE INDEX idx_analytics_logs_activity_type ON analytics_logs(activity_type);
    END IF;
END $$;

-- Risk assessments indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_risk_assessments_project_id') THEN
        CREATE INDEX idx_risk_assessments_project_id ON risk_assessments(project_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_risk_assessments_category') THEN
        CREATE INDEX idx_risk_assessments_category ON risk_assessments(risk_category);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_risk_assessments_priority') THEN
        CREATE INDEX idx_risk_assessments_priority ON risk_assessments(priority_level);
    END IF;
END $$;

-- SWOT analysis indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_swot_analysis_project_id') THEN
        CREATE INDEX idx_swot_analysis_project_id ON swot_analysis(project_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_swot_analysis_is_latest') THEN
        CREATE INDEX idx_swot_analysis_is_latest ON swot_analysis(is_latest);
    END IF;
END $$;

-- Success predictions indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_success_predictions_project_id') THEN
        CREATE INDEX idx_success_predictions_project_id ON success_predictions(project_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_success_predictions_is_latest') THEN
        CREATE INDEX idx_success_predictions_is_latest ON success_predictions(is_latest);
    END IF;
END $$;

-- Recommendations indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_recommendations_project_id') THEN
        CREATE INDEX idx_recommendations_project_id ON recommendations(project_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_recommendations_is_latest') THEN
        CREATE INDEX idx_recommendations_is_latest ON recommendations(is_latest);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_recommendations_priority') THEN
        CREATE INDEX idx_recommendations_priority ON recommendations(priority);
    END IF;
END $$;

-- Assessment reports indexes
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_assessment_reports_project_id') THEN
        CREATE INDEX idx_assessment_reports_project_id ON assessment_reports(project_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_assessment_reports_is_latest') THEN
        CREATE INDEX idx_assessment_reports_is_latest ON assessment_reports(is_latest);
    END IF;
END $$;

-- ===================================================
-- SAMPLE DATA (For Testing)
-- ===================================================

-- Insert a sample user (password: Test@123)
INSERT INTO users (name, email, password_hash, role) VALUES 
('John Doe', 'john@example.com', '$2b$10$abc123def456ghi789jklmno', 'user')
ON CONFLICT (email) DO NOTHING;

-- Insert a sample project
INSERT INTO projects (user_id, project_name, industry, business_model, target_market, budget, description) VALUES 
(1, 'AI Health Diagnostics', 'Healthcare', 'B2B', 'Hospitals and Clinics', 250000, 'AI-powered diagnostic tool for early disease detection')
ON CONFLICT DO NOTHING;

-- ===================================================
-- SAMPLE RISK ASSESSMENT
-- ===================================================
INSERT INTO risk_assessments (project_id, risk_category, risk_score, risk_description, priority_level, mitigation_strategy) VALUES 
(1, 'Financial', 65, 'Moderate financial risk due to initial investment requirements and extended R&D timeline', 'MEDIUM', 'Secure additional funding through grants and strategic partnerships'),
(1, 'Market', 45, 'Growing market demand with moderate competition', 'LOW', 'Differentiate through proprietary AI algorithms'),
(1, 'Technical', 70, 'High technical complexity with AI model development and regulatory compliance', 'HIGH', 'Invest in specialized AI talent and regulatory consultants'),
(1, 'Regulatory', 80, 'Significant regulatory requirements for healthcare AI applications', 'HIGH', 'Engage regulatory experts early in development process')
ON CONFLICT DO NOTHING;

-- ===================================================
-- SAMPLE SWOT ANALYSIS
-- ===================================================
INSERT INTO swot_analysis (project_id, strengths, weaknesses, opportunities, threats, summary, is_latest) VALUES 
(1, 
    '["Strong market demand for AI healthcare solutions", "Proprietary AI algorithms", "Experienced founding team", "Scalable business model"]',
    '["High development costs", "Long sales cycle", "Regulatory compliance requirements", "Limited initial funding"]',
    '["Growing telemedicine adoption", "Healthcare digital transformation", "Strategic partnerships with hospitals", "Government healthcare IT initiatives"]',
    '["Competition from established healthcare IT companies", "Changing regulatory landscape", "Data privacy concerns", "Technology disruption"]',
    'The project shows strong potential in the growing healthcare AI market, but faces significant regulatory and technical challenges that need careful management.',
    true
)
ON CONFLICT DO NOTHING;

-- ===================================================
-- SAMPLE SUCCESS PREDICTION
-- ===================================================
INSERT INTO success_predictions (project_id, success_probability, overall_risk_score, confidence_score, prediction_details, is_latest) VALUES 
(1, 72, 58, 85, '{"factors": {"market_growth": "high", "competition": "medium", "team_expertise": "high", "funding": "medium"}, "key_drivers": ["Market demand", "Proprietary technology", "Regulatory compliance"]}', true)
ON CONFLICT DO NOTHING;

-- ===================================================
-- SAMPLE RECOMMENDATIONS
-- ===================================================
INSERT INTO recommendations (project_id, recommendation_text, category, risk_mitigation, priority, expected_impact, is_latest) VALUES 
(1, 'Develop a comprehensive regulatory compliance strategy for healthcare AI applications', 'Regulatory', 'Engage regulatory consultants and legal experts early in the development process', 'HIGH', 'Reduces regulatory risk and accelerates market entry', true),
(1, 'Secure additional funding through healthcare innovation grants', 'Financial', 'Create a diversified funding strategy including grants, angel investors, and strategic partnerships', 'MEDIUM', 'Ensures adequate resources for development and regulatory compliance', true),
(1, 'Build strategic partnerships with healthcare providers', 'Market', 'Establish advisory board with healthcare industry experts', 'HIGH', 'Accelerates market validation and customer acquisition', true)
ON CONFLICT DO NOTHING;

-- ===================================================
-- SAMPLE ASSESSMENT REPORT
-- ===================================================
INSERT INTO assessment_reports (project_id, report_path, report_type, report_summary, is_latest) VALUES 
(1, '/reports/project_1_milestone2_report.pdf', 'PDF', 'Comprehensive assessment including risk analysis, SWOT, success prediction, and strategic recommendations', true)
ON CONFLICT DO NOTHING;

-- ===================================================
-- VIEWS FOR EASY REPORTING
-- ===================================================

-- Drop view if exists to avoid conflicts
DROP VIEW IF EXISTS project_assessments_latest;

-- Create view for latest assessments
CREATE VIEW project_assessments_latest AS
SELECT 
    p.project_id,
    p.project_name,
    p.industry,
    p.budget,
    p.created_at,
    sp.success_probability,
    sp.overall_risk_score,
    sp.confidence_score,
    sp.prediction_date,
    swot.strengths,
    swot.weaknesses,
    swot.opportunities,
    swot.threats,
    swot.summary as swot_summary,
    (SELECT json_agg(rec.*) FROM recommendations rec WHERE rec.project_id = p.project_id AND rec.is_latest = true) as recommendations
FROM projects p
LEFT JOIN success_predictions sp ON p.project_id = sp.project_id AND sp.is_latest = true
LEFT JOIN swot_analysis swot ON p.project_id = swot.project_id AND swot.is_latest = true;

COMMENT ON VIEW project_assessments_latest IS 'Latest assessment data for all projects';

-- ===================================================
-- SAMPLE QUERIES FOR RETRIEVING COMPLETE ASSESSMENT
-- ===================================================

-- Get complete project assessment
-- SELECT 
--     p.project_id,
--     p.project_name,
--     p.industry,
--     p.budget,
--     (SELECT json_agg(ra.*) FROM risk_assessments ra WHERE ra.project_id = p.project_id AND ra.is_latest = true) as risk_assessments,
--     (SELECT json_agg(swot.*) FROM swot_analysis swot WHERE swot.project_id = p.project_id AND swot.is_latest = true) as swot_analysis,
--     (SELECT json_agg(sp.*) FROM success_predictions sp WHERE sp.project_id = p.project_id AND sp.is_latest = true) as success_predictions,
--     (SELECT json_agg(rec.*) FROM recommendations rec WHERE rec.project_id = p.project_id AND rec.is_latest = true) as recommendations
-- FROM projects p
-- WHERE p.project_id = 1;

-- Get latest assessment for all projects
-- SELECT 
--     p.project_name,
--     p.industry,
--     sp.success_probability,
--     sp.overall_risk_score,
--     COUNT(DISTINCT ra.risk_id) as risk_count
-- FROM projects p
-- LEFT JOIN success_predictions sp ON p.project_id = sp.project_id AND sp.is_latest = true
-- LEFT JOIN risk_assessments ra ON p.project_id = ra.project_id AND ra.is_latest = true
-- GROUP BY p.project_name, p.industry, sp.success_probability, sp.overall_risk_score;